### ISSUE TITLE
Search functionality

### ISSUE THREAD

**Issue by Fuuzetsu** [chrisdone/lpaste#18]
Sometimes I vaguely remember someone asking a question or posting some code on lpaste that I want to find again without remembering much about it at all. It'd be great we could search the public pastes by title, author or paste content.

Currently we can browse all the pastes but we get 1541 pages of pastes without any apparent means to filter or sort them.

**Comment by aleiphoenix** [comment]
+1 for this if hpaste is setup for personal usage. Which has no chance Google would indexing search result. :)
